-- 강의 목록
CREATE TABLE LECTURE
(
    LECTURE_ID NUMBER PRIMARY KEY,
    MEMBER_ID NUMBER NOT NULL, -- ����ID
    LECTURE_TITLE VARCHAR2(50 CHAR) NOT NULL,
    LECTURE_PRICE NUMBER NOT NULL,
    LECTURE_SALES_COUNT NUMBER DEFAULT(0) NOT NULL,
    LECTURE_TOTAL_SCORE NUMBER DEFAULT(0) NOT NULL,
    LECTURE_REPLY_COUNT NUMBER DEFAULT(0) NOT NULL,
    LECTURE_LIKE_COUNT NUMBER DEFAULT(0) NOT NULL,
    LECTURE_DATE_CREATED TIMESTAMP DEFAULT(SYSDATE) NOT NULL
);

CREATE SEQUENCE LECTURE_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 100000
    NOCYCLE
    NOCACHE
    NOORDER;
    
-- 강의 동영상
CREATE TABLE LESSON
(
    LESSON_ID NUMBER PRIMARY KEY,
    LECTURE_ID NUMBER NOT NULL,
    LESSON_NAME VARCHAR2(30 CHAR),
    LESSON_URL VARCHAR2(100 CHAR)
);

CREATE SEQUENCE LESSON_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 100000
    NOCYCLE
    NOCACHE
    NOORDER;